server:
    port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/il_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # we have to tell initalize the table
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

#autherization
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:8383/oauth/check_token
#    client:
#      client-id: il
#      client-secret: pin

# user api call
#auth:
#  user:
#    url: http://localhost:8383/user
